FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

RUN apt-get update && apt-get install -y unzip curl
RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /root/vsdbg

WORKDIR /app
COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet dev-certs https --trust

ENTRYPOINT [ "dotnet", "watch", "run"]
