version: '3.8'
services:
    user_management_replicaSet_p:
        ports:
          - "${DB_PRIMARY_CONTAINER_PORT}:${DB_SERVER_PORT}"
    user_management_replicaSet_s_1:
        ports:
          - "${DB_SECONDARY_1_CONTAINER_PORT}:${DB_SERVER_PORT}"
    user_management_replicaSet_s_2:
        ports:
          - "${DB_SECONDARY_2_CONTAINER_PORT}:${DB_SERVER_PORT}"
