version: '3.8'
volumes:
    user_management_mongo_data: {}
    user_management_mongo_config_data: {}
services:
    user_management:
        container_name: user_management_integration_test
        build:
            context: ./
            dockerfile: ./tests/user_management_integration_tests/Dockerfile.integration_test
        environment:
            ASPNETCORE_ENVIRONMENT: "${ENVIRONMENT}"
            ENVIRONMENT: "${ENVIRONMENT}"
            Logging__LogLevel__Default: "${Logging_LogLevel_Default}"
            Logging__LogLevel__Microsoft.AspNetCore: "${Logging_LogLevel_Microsoft_AspNetCore}"
            Jwt__SecretKey: "${Jwt_SecretKey}"
            DB_NAME: "${DB_NAME}"
            DB_OPTIONS__IsSharded: "false"
            DB_OPTIONS__DatabaseName: "${DATABASE_NAME}"
            DB_OPTIONS__Host: user_management_mongodb
            DB_OPTIONS__Port: "${DB_SERVER_PORT}"
            DB_OPTIONS__Username: "${DB_USERNAME}"
            DB_OPTIONS__Password: "${DB_PASSWORD}"
        depends_on:
            - user_management_mongodb
    user_management_mongodb:
        container_name: user_management_mongodb
        image: mongo:4.4.18
        environment:
            MONGO_INITDB_DATABASE: "${DATABASE_NAME}"
            MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - user_management_mongo_data:/data/db
            - user_management_mongo_config_data:/data/configdb
