version: "3.8"
networks:
    db:
        driver: overlay
    backend:
        driver: overlay
secrets:
    Kestrel__Endpoints__Https__Certificate:
        external: true
    USER_MANAGEMENT_Jwt__SecretKey:
        external: true
    USER_MANAGEMENT_DB_NAME:
        external: true
    USER_MANAGEMENT_DB_OPTIONS__IsSharded:
        external: true
    USER_MANAGEMENT_DB_OPTIONS__DatabaseName:
        external: true
    USER_MANAGEMENT_DB_OPTIONS__Host:
        external: true
    USER_MANAGEMENT_DB_OPTIONS__Port:
        external: true
    USER_MANAGEMENT_DB_OPTIONS__Username:
        external: true
    CertificateP12:
        external: true
services:
    user_management:
        image: ghcr.io/hirbod-codes/user_management:latest
        ports:
            - '80:5000'
            - '443:5001'
        environment:
            DOTNET_GENERATE_ASPNET_CERTIFICATE: "false"
            USER_MANAGEMENT_MUST_NOT_USE_ENV_FILE: "true"
            USER_MANAGEMENT_ASPNETCORE_ENVIRONMENT: Production
            USER_MANAGEMENT_ENVIRONMENT: Production
            USER_MANAGEMENT_Logging__LogLevel__Default: warning
            USER_MANAGEMENT_Logging__LogLevel__Microsoft.AspNetCore: warning
            USER_MANAGEMENT_DB_OPTIONS__CertificateP12: /run/secrets/CertificateP12
            Kestrel__Endpoints__Https__Certificate__Path: /run/secrets/Kestrel__Endpoints__Https__Certificate
        secrets:
            - JWT__SECRET_KEY
            - USER_MANAGEMENT_DB_NAME
            - USER_MANAGEMENT_DB_OPTIONS__IsSharded
            - USER_MANAGEMENT_DB_OPTIONS__DatabaseName
            - USER_MANAGEMENT_DB_OPTIONS__Host
            - USER_MANAGEMENT_DB_OPTIONS__Port
            - USER_MANAGEMENT_DB_OPTIONS__Username
            - Kestrel__Endpoints__Https__Certificate
            - CertificateP12
        networks:
            - backend
            - db
