version: '3.8'
volumes:
    user_management_mongos_data: {}
    user_management_mongos_config_data: {}
    user_management_configServer1: {}
    user_management_configServer1_config: {}
    user_management_configServer2: {}
    user_management_configServer2_config: {}
    user_management_configServer3: {}
    user_management_configServer3_config: {}
    user_management_shardServer1: {}
    user_management_shardServer1_config: {}
    user_management_shardServer2: {}
    user_management_shardServer2_config: {}
    user_management_shardServer3: {}
    user_management_shardServer3_config: {}
services:
    user_management:
        container_name: user_management
        build:
            context: ./
            dockerfile: ./tests/user_management_integration_tests/Dockerfile.integration_test
        command: bash -c "sleep 240s && dotnet test --no-restore"
        volumes:
            - ./security/ca/ca.crt:/etc/ssl/certs/ca.crt
            - ./security/ca/ca.pem:/security/ca.pem
            - ./security/user_management/app.p12:/security/app.p12
        environment:
            USER_MANAGEMENT_MUST_NOT_USE_ENV_FILE: true
            USER_MANAGEMENT_ASPNETCORE_ENVIRONMENT: "${ENVIRONMENT}"
            USER_MANAGEMENT_ENVIRONMENT: "${ENVIRONMENT}"
            USER_MANAGEMENT_Logging__LogLevel__Default: "${Logging__LogLevel__Default}"
            USER_MANAGEMENT_Logging__LogLevel__Microsoft.AspNetCore: "${Logging__LogLevel__Microsoft_AspNetCore}"
            USER_MANAGEMENT_Jwt__SecretKey: "${Jwt__SecretKey}"
            USER_MANAGEMENT_DB_NAME: "${DB_NAME}"
            USER_MANAGEMENT_DB_OPTIONS__IsSharded: "${DB_OPTIONS__IsSharded}"
            USER_MANAGEMENT_DB_OPTIONS__CertificateP12: "${DB_OPTIONS__CertificateP12}"
            USER_MANAGEMENT_DB_OPTIONS__DatabaseName: "${DB_OPTIONS__DatabaseName}"
            USER_MANAGEMENT_DB_OPTIONS__Host: "${DB_OPTIONS__Host}"
            USER_MANAGEMENT_DB_OPTIONS__Port: "${DB_OPTIONS__Port}"
            USER_MANAGEMENT_DB_OPTIONS__Username: "${DB_OPTIONS__Username}"
        depends_on:
            - user_management_mongodb
