version: '3.8'
volumes:
    user_management_mongodb_data: {}
    user_management_mongodb_config_data: {}
    user_management_configServer1_data: {}
    user_management_configServer1_config_data: {}
    user_management_configServer2_data: {}
    user_management_configServer2_config_data: {}
    user_management_configServer3_data: {}
    user_management_configServer3_config_data: {}
    user_management_shardServer1_data: {}
    user_management_shardServer1_config_data: {}
    user_management_shardServer2_data: {}
    user_management_shardServer2_config_data: {}
    user_management_shardServer3_data: {}
    user_management_shardServer3_config_data: {}
services:
    user_management_mongodb:
        container_name: user_management_mongodb
        image: mongo:4.4.18
        command: bash -c "/mongodb/mongos_server.sh"
        environment:
            dbUsername: ${CRT_USERNAME}
            dbAdminUsername: ${DB_USERNAME}
            dbPassword: "${DB_PASSWORD}"
            dbName: ${DB_DATABASE_NAME}
            dbPort: ${DB_SERVER_PORT}
            configReplSet: user_management_configReplicaSet
            configMember0: user_management_configServer1
            configMember1: user_management_configServer2
            configMember2: user_management_configServer3
            shardReplSet: user_management_shardReplicaSet
            shardMember0: user_management_shardServer1
            shardMember1: user_management_shardServer2
            shardMember2: user_management_shardServer3
        volumes:
            - user_management_mongodb_data:/data/db
            - user_management_mongodb_config_data:/data/configdb
            - ./mongodb/mongos_server.sh:/mongodb/mongos_server.sh
            - ./security/ca/ca.crt:/security/ca.pem
            - ./security/user_management_mongodb_member/app.pem:/security/member.pem
            - ./security/user_management_mongodb/app.pem:/security/app.pem
    user_management_configServer1:
        container_name: user_management_configServer1
        image: mongo:4.4.18
        command: bash -c "/mongodb/config_server.sh"
        environment:
            dbPort: ${DB_SERVER_PORT}
            replSet: user_management_configReplicaSet
            member0: user_management_configServer1
            member1: user_management_configServer2
            member2: user_management_configServer3
        volumes:
            - user_management_configServer1_data:/data/db
            - user_management_configServer1_config_data:/data/configdb
            - ./mongodb/config_server.sh:/mongodb/config_server.sh
            - ./security/ca/ca.crt:/security/ca.pem
            - ./security/user_management_configServer1_member/app.pem:/security/member.pem
            - ./security/user_management_configServer1/app.pem:/security/app.pem
    user_management_configServer2:
        container_name: user_management_configServer2
        image: mongo:4.4.18
        command: bash -c "/mongodb/secondary_config_server.sh"
        environment:
            replSet: user_management_configReplicaSet
            dbPort: ${DB_SERVER_PORT}
        volumes:
            - user_management_configServer2_data:/data/db
            - user_management_configServer2_config_data:/data/configdb
            - ./mongodb/secondary_config_server.sh:/mongodb/secondary_config_server.sh
            - ./security/ca/ca.crt:/security/ca.pem
            - ./security/user_management_configServer2_member/app.pem:/security/member.pem
            - ./security/user_management_configServer2/app.pem:/security/app.pem
    user_management_configServer3:
        container_name: user_management_configServer3
        image: mongo:4.4.18
        command: bash -c "/mongodb/secondary_config_server.sh"
        environment:
            replSet: user_management_configReplicaSet
            dbPort: ${DB_SERVER_PORT}
        volumes:
            - user_management_configServer3_data:/data/db
            - user_management_configServer3_config_data:/data/configdb
            - ./mongodb/secondary_config_server.sh:/mongodb/secondary_config_server.sh
            - ./security/ca/ca.crt:/security/ca.pem
            - ./security/user_management_configServer3_member/app.pem:/security/member.pem
            - ./security/user_management_configServer3/app.pem:/security/app.pem
    user_management_shardServer1:
        container_name: user_management_shardServer1
        image: mongo:4.4.18
        command: bash -c "/mongodb/shard_server.sh"
        environment:
            dbPort: ${DB_SERVER_PORT} 
            replSet: user_management_shardReplicaSet 
            member0: user_management_shardServer1 
            member1: user_management_shardServer2 
            member2: user_management_shardServer3
        volumes:
            - user_management_shardServer1_data:/data/db
            - user_management_shardServer1_config_data:/data/configdb
            - ./mongodb/shard_server.sh:/mongodb/shard_server.sh
            - ./security/ca/ca.crt:/security/ca.pem
            - ./security/user_management_shardServer1_member/app.pem:/security/member.pem
            - ./security/user_management_shardServer1/app.pem:/security/app.pem
    user_management_shardServer2:
        container_name: user_management_shardServer2
        image: mongo:4.4.18
        command: bash -c "/mongodb/secondary_shard_server.sh"
        environment:
            replSet: user_management_shardReplicaSet
            dbPort: ${DB_SERVER_PORT}
        volumes:
            - user_management_shardServer2_data:/data/db
            - user_management_shardServer2_data:/data/configdb
            - ./mongodb/secondary_shard_server.sh:/mongodb/secondary_shard_server.sh
            - ./security/ca/ca.crt:/security/ca.pem
            - ./security/user_management_shardServer2_member/app.pem:/security/member.pem
            - ./security/user_management_shardServer2/app.pem:/security/app.pem
    user_management_shardServer3:
        container_name: user_management_shardServer3
        image: mongo:4.4.18
        command: bash -c "/mongodb/secondary_shard_server.sh"
        environment:
            replSet: user_management_shardReplicaSet
            dbPort: ${DB_SERVER_PORT}
        volumes:
            - user_management_shardServer3_data:/data/db
            - user_management_shardServer3_config_data:/data/configdb
            - ./mongodb/secondary_shard_server.sh:/mongodb/secondary_shard_server.sh
            - ./security/ca/ca.crt:/security/ca.pem
            - ./security/user_management_shardServer3_member/app.pem:/security/member.pem
            - ./security/user_management_shardServer3/app.pem:/security/app.pem
