version: '3.8'
volumes:
    user_management_mongo_data: {}
    user_management_mongo_config_data: {}
services:
    user_management:
        container_name: user_management
        build:
            context: ./
            dockerfile: ./src/user_management/Dockerfile.development
        volumes:
            - ./src/user_management:/app:rw
        ports:
            - '${APP_HTTP_PORT}:5000'
            - '${APP_HTTPS_PORT}:5001'
        environment:
            USER_MANAGEMENT_MUST_NOT_USE_ENV_FILE: true
            USER_MANAGEMENT_ASPNETCORE_ENVIRONMENT: "${ENVIRONMENT}"
            USER_MANAGEMENT_ENVIRONMENT: "${ENVIRONMENT}"
            USER_MANAGEMENT_DOTNET_WATCH_RESTART_ON_RUDE_EDIT: true
            USER_MANAGEMENT_Logging__LogLevel__Default: "${LOGGING_LOG_LEVEL_DEFAULT}"
            USER_MANAGEMENT_Logging__LogLevel__Microsoft.AspNetCore: "${LOGGING_LOG_LEVEL_MICROSOFT_ASPNETCORE}"
            USER_MANAGEMENT_Jwt__SecretKey: "${JWT_SECRET_KEY}"
            USER_MANAGEMENT_DB_NAME: "${DB_NAME}"
            USER_MANAGEMENT_DB_OPTIONS__IsSharded: "${DB_OPTIONS__IsSharded}"
            USER_MANAGEMENT_DB_OPTIONS__DatabaseName: "${DB_OPTIONS__DatabaseName}"
            USER_MANAGEMENT_DB_OPTIONS__Host: "${DB_OPTIONS__Host}"
            USER_MANAGEMENT_DB_OPTIONS__Port: "${DB_OPTIONS__Port}"
            USER_MANAGEMENT_DB_OPTIONS__Username: "${DB_OPTIONS__Username}"
            USER_MANAGEMENT_DB_OPTIONS__Password: "${DB_OPTIONS__Password}"
        depends_on:
            - user_management_mongodb
    user_management_mongo_express:
        container_name: user_management_mongo_express
        image: mongo-express:0.54.0
        restart: always
        ports:
            - '${ME_CONTAINER_PORT}:8081'
        depends_on:
            - user_management_mongodb
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: "${ME_CONFIG_BASICAUTH_USERNAME}"
            ME_CONFIG_BASICAUTH_PASSWORD: "${ME_CONFIG_BASICAUTH_PASSWORD}"
            ME_CONFIG_MONGODB_SERVER: user_management_mongodb
            ME_CONFIG_MONGODB_PORT: "${DB_SERVER_PORT}"
            ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    user_management_mongodb:
        container_name: user_management_mongodb
        image: mongo:4.4.18
        ports:
            - '${DB_CONTAINER_PORT}:${DB_SERVER_PORT}'
        environment:
            MONGO_INITDB_DATABASE: "${DB_DATABASE_NAME}"
            MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - user_management_mongo_data:/data/db
            - user_management_mongo_config_data:/data/configdb
