FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

RUN apt-get update && apt-get install -y unzip curl
RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /root/vsdbg

WORKDIR /app
COPY ./tests/user_management_unit_tests/user_management_unit_tests.csproj ./tests/user_management_unit_tests/
COPY ./src/user_management/user_management.csproj ./src/user_management/

WORKDIR /app/tests/user_management_unit_tests
RUN dotnet restore -v d

WORKDIR /app
COPY ./tests/user_management_unit_tests/ ./tests/user_management_unit_tests/
COPY ./src/user_management/ ./src/user_management/

RUN dotnet dev-certs https --trust

WORKDIR /app/tests/user_management_unit_tests
CMD dotnet test --no-restore
