FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /app

COPY ./user_management.sln .
COPY ./src/user_management/user_management.csproj ./src/user_management/
COPY ./tests/user_management_unit_tests/user_management_unit_tests.csproj ./tests/user_management_unit_tests/
COPY ./tests/user_management_integration_tests/user_management_integration_tests.csproj ./tests/user_management_integration_tests/

RUN dotnet restore -f --force-evaluate -v d

COPY ./tests/ ./tests/
COPY ./src/ ./src/

RUN dotnet dev-certs https --trust

CMD dotnet test --no-restore --filter="FullyQualifiedName~user_management_unit_tests"
