FROM mcr.microsoft.com/dotnet/sdk:7.0

COPY ./security/ca/ca.crt /etc/ssl/certs/

WORKDIR /project

COPY ./src/user_management/user_management.csproj ./
RUN dotnet restore -v d

RUN apt update && apt install openssl

COPY ./src/user_management/ ./

RUN dotnet publish --disable-build-servers --no-restore -c Release -o /publish

WORKDIR /publish

EXPOSE 5001 5000
CMD dotnet user_management.dll
