FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

RUN apt-get update && apt-get install -y unzip curl
RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /root/vsdbg

WORKDIR /app

COPY ./src/user_management/user_management.csproj ./
RUN dotnet restore -v d

COPY ./src/user_management/ ./

RUN dotnet dev-certs https --trust

CMD dotnet watch run --no-restore
