FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /app
COPY ./tests/user_management_integration_tests/user_management_integration_tests.csproj ./tests/user_management_integration_tests/
COPY ./src/user_management/user_management.csproj ./src/user_management/

WORKDIR /app/tests/user_management_integration_tests
RUN dotnet restore -v d

WORKDIR /app
COPY ./tests/user_management_integration_tests/ ./tests/user_management_integration_tests/
COPY ./src/user_management/ ./src/user_management/

RUN dotnet dev-certs https --trust

WORKDIR /app/tests/user_management_integration_tests
CMD dotnet test --no-restore
