on:
    workflow_run: 
        workflows: test
        types: completed
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{secrets.DOCKER_HUB_USERNAME}}
                  password: ${{secrets.DOCKER_HUB_TOKEN}}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Github Container registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{github.repository_owner}}
                password: ${{secrets.PACKAGE_ACCESS_TOKEN}}

            - name: Build user_management service' docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: './src/user_management/Dockerfile.production'
                platforms: linux/amd64,linux/arm64
                push: true
                tags: |
                    ghcr.io/${{github.repository}}:latest
