name: build

on:
    repository_dispatch:
        types: [on-new-version]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            packages: write

        steps:
            - 
                name: Checkout
                uses: actions/checkout@v4

            - 
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            - 
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            - 
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{secrets.DOCKER_HUB_USERNAME}}
                    password: ${{secrets.DOCKER_HUB_TOKEN}}

            - 
                name: Login to GHCR
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{github.repository_owner}}
                    password: ${{secrets.GITHUB_TOKEN}}

            - 
                name: Docker Metadata for Final Image Build
                id: docker_meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }},ghcr.io/${{github.repository}}
                    flavor: |
                        latest=false
                    tags: |
                        type=semver,pattern={{version}},value=${{ github.event.client_payload.version }}

            - 
                name: Build and push user_management service docker image  to GHCR and Docker Hub
                uses: docker/build-push-action@v5
                with:
                    push: true
                    context: ./
                    file: ./src/user_management/Dockerfile.production
                    tags: ${{ steps.docker_meta.outputs.tags }}
                    labels: ${{ steps.docker_meta.outputs.labels }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
                    platforms: linux/amd64,linux/arm64
